# Generated by Django 4.2.16 on 2024-11-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('match_result', models.CharField(choices=[('perfect_win', '完全勝利'), ('difference_win', '点差勝利'), ('draw', '引き分け'), ('difference_lose', '点差敗北'), ('perfect_lose', '完全敗北')], max_length=15)),
                ('match_point', models.IntegerField()),
                ('match_leader', models.CharField(max_length=255)),
                ('memo', models.TextField()),
            ],
        ),
    ]
